name: Dependent Task
description: A task that requires other tasks to be completed first
labels: "dependent"
body:
  - type: markdown
    attributes:
      value: |
        To avoid confusions please describe the task in a clear and concise manner.
  - type: textarea
    id: dependencies
    attributes:
      label: "⚠️ Dependencies:"
      description: "List dependencies using markdown checklist syntax. Github automatically links the issue by providing the number E.g., `- [] #2`"
      placeholder: |
        - [ ] #1
        - [ ] #2
        - [ ] #3
      value: "- [ ] "
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "📝 Description:"
      description: "Clearly and concisely describe the task."
      placeholder: |
        Create a function that accepts the string "Hello" as an input and outputs "Hello World!"
    validations:
      required: true
  - type: textarea
    id: todos
    attributes:
      label: "✅ TODOS:"
      description: "Break down the task into a list of `TODOS` using markdown checklist syntax. E.g., `- [] Implement validation for the input string `"
      placeholder: |
        - [ ] TODO 1
        - [ ] TODO 2
        - [ ] TODO 3
      value: "- [ ] "
    validations:
      required: false
