name: Deploy FastAPI Backend

on:
  push:
    branches: [test-cicd]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_P_KEY }}
          script: |
            cd ~/3gpp_app/p2_backend
            git pull
            echo "hello" > hello.text
            source ~/.profile


            uv sync --frozen --no-cache
            sudo systemctl restart api.service
